name: "Srinivas Yedhuri's Blog"
description: "Blogging about Web Technologies"
meta_description: "A blog by Srinivas Yedhuri"

aboutPage: true

markdown: redcarpet
#highlighter: pygments
highlighter: rouge 

gems: [jekyll-paginate]
paginate: 7
paginate_path: "page:num"
baseurl: /
domain_name: 'http://anotetomyself.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus: true
disqus_shortname: 'anotetomyselfcom'

# Details for the RSS feed generator
url:            'http://anotetomyself.com'
author:         'Srinivas Yedhuri'
authorTwitter:  'sri429'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
